### ISSUE TITLE
Unable to find variable store.

### ISSUE THREAD

**Issue by geeuk** [XDleader555/grub_setup_var#4]
Hi,

Thanks for your Grub tool, this is the only that I could work on my Inspiron 7490 that has UEFI boot so grub 2.03 you complied works very good.

I am trying to replicate https://www.reddit.com/r/Dell/comments/fzv599/xps_7590_160_uefi_unlock_undervolting_and_remove/

The issue I have is when I try to modify the bios I get the error. **Unable to find variable store.**

Thanks

**Comment by XDleader555** [comment]
Can you upload your Setup IFR.txt or copy to a pastebin? The command differs on this fork slightly.
I have the [Setup IFR.txt for the XPS13-9365](https://raw.githubusercontent.com/XDleader555/XPS13-9365_Fixes/master/2.9.0%20Setup%20IFR.txt) as an example.

The typical usage for this version of setup_var uses the following format:
```
setup_var storename offset [setval]
```

Notice that **storename** is an extra parameter. Normally this would be `Setup`, but your variable might be located under a different store name such as `SetupCpuFeatures`

**If it's VarStore 0x1, then just use `Setup` as the storename.**

For example, on my **XPS13-9365**, notice how CFG lock is actually under VarStore 0x3

```
0x1B6DB 	Form: View/Configure CPU Lock Options, FormId: 0x1012 {01 86 12 10 DA 00}
0x1B6E1 		One Of: CFG Lock, VarStoreInfo (VarOffset/VarName): 0x3C, VarStore: 0x3, QuestionId: 0x2DC, Size: 1, Min: 0x0, Max 0x1, Step: 0x0 {05 91 A2 02 A3 02 DC 02 03 00 3C 00 10 10 00 01 00}
0x1B6F2 			One Of Option: Disabled, Value (8 bit): 0x0 {09 07 04 00 00 00 00}
0x1B6F9 			One Of Option: Enabled, Value (8 bit): 0x1 (default) {09 07 03 00 30 00 01}
0x1B700 		End One Of {29 02}
0x1B702 		One Of: Overclocking Lock, VarStoreInfo (VarOffset/VarName): 0xEB, VarStore: 0x3, QuestionId: 0x2DD, Size: 1, Min: 0x0, Max 0x1, Step: 0x0 {05 91 9E 02 9F 02 DD 02 03 00 EB 00 10 10 00 01 00}
0x1B713 			One Of Option: Disabled, Value (8 bit): 0x0 (default) {09 07 04 00 30 00 00}
0x1B71A 			One Of Option: Enabled, Value (8 bit): 0x1 {09 07 03 00 00 00 01}
0x1B721 		End One Of {29 02}
0x1B723 	End Form {29 02}
```

At the top of the file, VarStores are listed

```
0x122E9 	VarStoreEFI: VarStoreId: 0x2 [72C5E28C-7783-43A1-8767-FAD73FCCAFA4], Attrubutes: 7, Size: 1FE, Name: SaSetup {26 22 02 00 8C E2 C5 72 83 77 A1 43 87 67 FA D7 3F CC AF A4 07 00 00 00 FE 01 53 61 53 65 74 75 70 00}
0x1230B 	VarStoreEFI: VarStoreId: 0x4 [5432122D-D034-49D2-A6DE-65A829EB4C74], Attrubutes: 7, Size: 2D, Name: MeSetup {26 22 04 00 2D 12 32 54 34 D0 D2 49 A6 DE 65 A8 29 EB 4C 74 07 00 00 00 2D 00 4D 65 53 65 74 75 70 00}
0x1232D 	VarStoreEFI: VarStoreId: 0x3 [B08F97FF-E6E8-4193-A997-5E9E9B0ADB32], Attrubutes: 7, Size: 20B, Name: CpuSetup {26 23 03 00 FF 97 8F B0 E8 E6 93 41 A9 97 5E 9E 9B 0A DB 32 07 00 00 00 0B 02 43 70 75 53 65 74 75 70 00}
0x12350 	VarStoreEFI: VarStoreId: 0x5 [4570B7F1-ADE8-4943-8DC3-406472842384], Attrubutes: 7, Size: 662, Name: PchSetup {26 23 05 00 F1 B7 70 45 E8 AD 43 49 8D C3 40 64 72 84 23 84 07 00 00 00 62 06 50 63 68 53 65 74 75 70 00}
0x12373 	VarStoreEFI: VarStoreId: 0x1 [EC87D643-EBA4-4BB5-A1E5-3F3E36B20DA9], Attrubutes: 7, Size: 549, Name: Setup {26 20 01 00 43 D6 87 EC A4 EB B5 4B A1 E5 3F 3E 36 B2 0D A9 07 00 00 00 49 05 53 65 74 75 70 00}
```

VarStore 0x3 is actually `CpuSetup`. 
The command I would use to disable `CFG Lock` on my **XPS13-9365** would be:
```
setup_var CpuSetup 0x3C 0x0
```

**Comment by geeuk** [comment]
Thank you. After reading your detailed response I checked the commands as you said I should of entered this **setup_var CpuSetup 0x3C 0x0** 

Now I have my under volt back thanks to you :)

**Comment by Thulli03** [comment]
What would it mean if I didn't have a CpuSetup value under the VarStoreID section?

I also don't see any rows that start with **VarStoreEFI**: VarStoreID

**Comment by Lacxp** [comment]
I don't see it neither. Here is my Cpu Lock Options (CFG Lock and Overclocking Lock):

Form: View/Configure CPU Lock Options, Form ID: 0x1012 {01 86 12 10 D7 01}
0x7A0E6 	Setting: CFG Lock, Variable: 0x43 {05 91 B4 03 B5 03 30 01 03 00 43 00 10 10 00 01 00}
0x7A0F7 		Option: Disabled, Value: 0x0 {09 07 04 00 00 00 00}
0x7A0FE 		Option: Enabled, Value: 0x1 {09 07 03 00 30 00 01}
0x7A105 	End of Options {29 02}
0x7A107 	Setting: Overclocking Lock, Variable: 0xDF {05 91 B0 03 B1 03 31 01 03 00 DF 00 10 10 00 01 00}
0x7A118 		Option: Disabled, Value: 0x0 {09 07 04 00 00 00 00}
0x7A11F 		Option: Enabled, Value: 0x1 {09 07 03 00 30 00 01}
0x7A126 	End of Options {29 02}
0x7A128 End Form {29 02}

I tried with Varstore "CpuSetup", but did not work in terms of undervolting. Any ideas?
Thank You :)
